from addSoc import addSoc as add

def addSoc():
	socs = [
	"180 Degrees Consulting",
	"601 Prayer Community (KOSTA 601)",
	"Accounting Society",
	"Actuarial Society",
	"Advent Hope",
	"Adventurers Society",
	"Advertising & Public Relations Society",
	"AIESEC",
	"Albury Wodonga Medical Students Society",
	"Alternative Investment Society",
	"American Institute of Aeronautics and Astronautics (AIAA)",
	"Animal Voices",
	"Animation Society",
	"AnimeUNSW",
	"Anjali Tamil Society",
	"Architecture Society",
	"Art & Drawing Society",
	"Arts Society",
	"Australasian Union of Jewish Students (AUJS)",
	"Australia China Youth Association (ACYA)",
	"Australian Relief Organisation",
	"Aviation Society",
	"Baking Society",
	"Bangladeshi Society",
	"Barbell Club",
	"Basketball Society",
	"Basser College",
	"B-Grade Society",
	"Bike Club",
	"Biohacking Society UNSW",
	"Biomedical Engineering Students Society",
	"BIOSOC",
	"Biosphere",
	"Biotechnology & Biomolecular Science Society",
	"BIT ISM Student Association",
	"BlizzSoc",
	"Bluesat",
	"Boardgames and RPG Society",
	"Bookworm Society",
	"Built Environment Student Association",
	"Business Society",
	"BusinessONE UNSW",
	"Campus Runners",
	"Car Society",
	"Catholic Asian Students Society",
	"Catholic Society",
	"Cheer and Dance Society",
	"Chemical Engineering Undergraduate Society",
	"Chess Club",
	"Chinese Christian Fellowship",
	"Chinese Debating Club",
	"Chinese Musician Society",
	"Chinese Student Association",
	"Chinese Theatrical Society",
	"Chinmaya Yuva Kendra (CHYK)",
	"Christian Union",
	"Cinematic Society",
	"Circus Society",
	"Civil & Environmental Engineering Research Student Association",
	"Civil and Environmental Engineering Society",
	"Civil and Environmental Postgraduate Coursework Association",
	"Close-up Magic Society",
	"Cloud Communication Computing Club",
	"Coffs Harbour Undergraduate Medical Students",
	"Colombo House Residents Club",
	"Come & See",
	"Commerce (International) Society",
	"Compassion UNSW",
	"Computer Enthusiasts Society",
	"Conservative Club of UNSW",
	"Cooking Society",
	"Co-op Society",
	"Coptic Society",
	"CREATE NSW Inc.",
	"Creston College Student Society",
	"Criminology Society",
	"CryptoSoc UNSW",
	"CSE Revue",
	"CSE Society",
	"CueSports Society",
	"D2MG Hip Hop Society",
	"Data Science Society",
	"Debating Society",
	"Didi Foundation at UNSW",
	"Disney Society",
	"Doctor Who Society",
	"Dog Appreciation Society",
	"Dragon Boating",
	"Economics Society",
	"Education Society",
	"Electrical Engineering & Telecommunications Society",
	"Enactus UNSW",
	"Engineering World Health (UNSW Chapter)",
	"Engineers Without Borders",
	"Engiqueers",
	"Enrich Mandarin Bible Study",
	"Esports Club",
	"Exchange Society",
	"Exotic Beer Society",
	"Faculty of Engineering Student Society",
	"Falun Dafa",
	"Fashion and Beauty Society",
	"Fellowship of Orthodox Christian University",
	 "Students (FOCUS)",
	"Fig Tree Hall College",
	"Filipino Students Society",
	"Film Society",
	"Finance and Banking Society",
	"Financial Management Association of Australia (FMAA)",
	"Financial Planning Student Group",
	"Fit Club",
	"Food For All Association",
	"Food Lovers Society",
	"Food Science Association",
	"Forex Society",
	"Fred Hollows Society",
	"French Society",
	"Friends of Alpha Epsilon Pi UNSW",
	"Game Development Society",
	"Game of Thrones Society",
	"GEOSoc",
	"Giving Sight",
	"Gliding Society",
	"Goldstein College",
	"Graduate Student Association",
	"Handbell Society",
	"Hellenic Society",
	"Hepatitis B Free",
	"Hillsong Campus Club",
	"Hindu Society",
	"History Society",
	"Hong Kong Student Association",
	"I Heart UNSW",
	"Indian Society",
	"Indonesian Students Association",
	"International House Residents Society",
	"International Studies Society",
	"International Youth and Students for Social Equality (IYSSE)",
	"Investing for Charity",
	"Iranian Student Association",
	"Italian Society",
	"Knitting and Crochet Society",
	"Korean Students Association",
	"Kpop Society",
	"Latin Dance Society",
	"Law Revue Society",
	"Law Society",
	"League of Legends Society",
	"LEGO Society",
	"Lets Talk Club",
	"Liberal Club",
	"Libertarian Society",
	"Life Drawing Society",
	"LifeChoice UNSW",
	"Mahjong Society",
	"Make Club",
	"Malaysian Students Organisation",
	"Management Society",
	"Marketing Analytics Society",
	"Marketing Society",
	"Materials Science and Engineering Postgraduate Society",
	"Materials Science and Engineering Society",
	"Mathematics Society",
	"Mature Age Student Society",
	"Mechatronics Society",
	"Med Revue Society",
	"Media Society",
	"Medical Outreachers Australia",
	"Medical Society",
	"MentorMe UNSW",
	"Metal Society",
	"Middle Eastern Food and Culture Society",
	"Mine PostGrad Society",
	"Minecraft Society",
	"Ministry of Dance Society (MODSoc)",
	"Modeling Society",
	"Music Society of UNSW",
	"Musical Theatre Society",
	"Muslim Students Association",
	"Myanmar Student Society",
	"Myall Club",
	"Nanoscience & Nanotechnology Society",
	"Negotiation Society",
	"Nepalese Society",
	"Nerf Society",
	"Neuroscience Society",
	"New College Student Association",
	"New College Village Social Club",
	"New South Wales Ski & Board Club (NEWSKI)",
	"New South Wales Uni Theatrical Society (NUTS)",
	"Nigerian Students Association",
	"Nippon Students Association",
	"Organisation of Planning Students",
	"osu! Society",
	"Overseas Christian Fellowship",
	"Oxfam UNSW",
	"Pacific Island Countries and Territories Student Association UNSW",
	"Pakistani Students Society",
	"Personal Finance Society",
	"Petroleum Engineering Student Society",
	"Philip Baxter College",
	"PhotoClub",
	"Physics Society",
	"Poetry Society UNSW",
	"Poker Society",
	"Polity",
	"Port Medical Society",
	"Project Hope UNSW",
	"Psychology Society",
	"Puzzle Society",
	"Quidditch Society",
	"Real Estate Society",
	"Redback Racing Team",
	"Reformed Evangelical Fellowship",
	"Renewable Energy Society",
	"Robogals",
	"Royal Society of Frozen Desserts",
	"Rural Allied Health and Medical Society",
	"Saudi Students Union",
	"Save The Children UNSW Student Action Group",
	"School of Mechanical and Manufacturing Engineering Student Society",
	"Science Society",
	"Security Society",
	"Shalom College Residents Society",
	"Shanghainese Society",
	"Sikh Students Association",
	"Singapore Students Association",
	"Slavic Society",
	"Smash Brothers",
	"Sneakers and Streetwear Society",
	"Social Soccer Society",
	"Social Work Student Association",
	"Socialist Alternative Club",
	"Society for Vietnamese International Students at UNSW",
	"Society of Medical Innovation",
	"Society of Orchestra and Pipers",
	"Society of Statistics",
	"Society of Telecommunications and Electrical Engineers for Postgraduates",
	"Society of Wahyanites",
	"Space and Astronomy Society",
	"Spocksoc",
	"Sri Lankan Students Society",
	"St John Ambulance Student Society",
	"Sports Business Club",
	"StartUp Link",
	"String Ensemble",
	"Student Outreach to the World",
	"Students for Nuclear Energy",
	"Students for Palestine UNSW",
	"Students of Advanced Mathematics and Science",
	"Students of Chemistry Society",
	"Students of EMBL Australia for Single Molecule Science",
	"Students of Medical Science Society",
	"Sunswift",
	"Surveying Society",
	"Sydney International Christian Church",
	"Synthetic Biology Society",
	"Tabletop Wargaming Society",
	"Taiwanese Students Association",
	"Taxation and Business Law Society",
	"Tea & Coffee Society",
	"Teach Learn Grow UNSW",
	"Thai Students Society",
	"Tolkien Society",
	"Trading Card Game Society",
	"Tricking Society",
	"Turkish Society",
	"United Nations Society",
	"University Network for Investing & Trading (UNIT)",
	"University of New South Wales Hall",
	"UNSW Agnostics, Athiests and Humanists",
	"UNSW Christian Students",
	"UNSW Consulting Club",
	"UNSW Microfinance Consulting Group",
	"VaderSoc",
	"Variety Childrens Society - UNSW",
	"Vegetarian Society",
	"Vietnamese Students Association",
	"Vinnies Society",
	"Vision Generation",
	"Wagga Rural UNSW Medical Society",
	"Wandering Society",
	"Warrane College",
	"We Act",
	"Women in Creative Business",
	"Women in Engineering",
	"Women In Renewable Energy",
	"Women In Science Society",
	"Women in Technology",
	"Yoga Club",
	"Yoyo Society UNSW",
	]

	for i in socs:
		add(i, "", 0)

if __name__ == "__main__":
	addSoc()
